import type { ChunkManifest } from './manifest'

/**
 * Generated by scripts/build.mjs. Do not edit.
 *
 * Checked in as an empty stub: a fresh clone must type-check and test before
 * anything has been built. A real build overwrites this file, and the built
 * copy is never committed - the URLs in it carry the environment they were
 * built for.
 */
export const MANIFEST: ChunkManifest = {}

export const VERSION = "0.0.0-dev"
