import type { ChunkManifest } from './manifest'

/** Generated by scripts/build.mjs. Do not edit. */
export const MANIFEST: ChunkManifest = {
    "color": {"url":"https://cdn.flowappz.cloud/form-fields-pro/staging/5.1.10/chunks/field-color.d3629f8dcdee.js","integrity":"sha384-IzeCdK/VkrZqRI5H+mkvLdyKpCkDmYjIX5unVLV6jH5J6Of+w+SWmCu7ZegTpRjQ","deps":["ui-popover"],"bytes":8411},
    "date": {"url":"https://cdn.flowappz.cloud/form-fields-pro/staging/5.1.10/chunks/field-date.d612c2eefbd5.js","integrity":"sha384-QEbyrHUI02e3pLK04Mu4cbq1Pj1G6KziEzMhQApNizCYRN4B5VrDyR9H8sa6LxYq","deps":["ui-popover"],"bytes":16561},
    "file": {"url":"https://cdn.flowappz.cloud/form-fields-pro/staging/5.1.10/chunks/field-file.b8cad3e7765e.js","integrity":"sha384-2lv/E+e+1v9gBUUIndfopJZ+Vwcnwgps8t6uxjWDV1/CDpe07hP0hjPQY8zUaQdM","deps":[],"bytes":7575},
    "nps": {"url":"https://cdn.flowappz.cloud/form-fields-pro/staging/5.1.10/chunks/field-nps.6597c0f7afe9.js","integrity":"sha384-bCRBXHH+8JO28Y2vM8ofXfRRWsG+iSctm6ieeqhVNIMF9bkyLEJbcHd4tXOC107y","deps":[],"bytes":9899},
    "phone": {"url":"https://cdn.flowappz.cloud/form-fields-pro/staging/5.1.10/chunks/field-phone.8ec2e05aa679.js","integrity":"sha384-PH56/tX8Ghl34GWiRZsE1amOwi9zhJX1iopKllFwxV5mPxjcdYZdAzUSDd2lVWe0","deps":["ui-popover"],"bytes":14919},
    "select": {"url":"https://cdn.flowappz.cloud/form-fields-pro/staging/5.1.10/chunks/field-select.1d5455f1d2a9.js","integrity":"sha384-y/QI+gMO5UNPKCSXQNrg8A6G++9T4ZAQkU+GuYDaj/zLZv3cOjZFv2BObzcQBHZ/","deps":["ui-popover"],"bytes":5710},
    "slider": {"url":"https://cdn.flowappz.cloud/form-fields-pro/staging/5.1.10/chunks/field-slider.3f4ccfcbb037.js","integrity":"sha384-K1WFQt5xtfR5L9vSULgRu+LMqQY8W7eAbgYp/jrrySBsftOAbYUWI9tV1xRI5pma","deps":[],"bytes":8765},
    "ui-popover": {"url":"https://cdn.flowappz.cloud/form-fields-pro/staging/5.1.10/chunks/ui-popover.22445fc9d3b4.js","integrity":"sha384-fkHyf6rzX0BnAYSadiwedNtIE5ULm9DRdzSXNUN/ja9LGG9wZBxSu0ksKQr9AEGX","deps":[],"bytes":7691},
    "userip": {"url":"https://cdn.flowappz.cloud/form-fields-pro/staging/5.1.10/chunks/field-userip.4572c36abc1b.js","integrity":"sha384-VeaU20mJjq4cooZ+BgMGDJ2L2eLoC77gLZqvVn/4mL2vQDiPIU7y5BYhhGwQuaIw","deps":[],"bytes":799},
}

export const VERSION = "5.1.10"
